POST http://localhost:8080/api/users/create HTTP/1.1
Content-Type: application/json

{
    "username": "jamie",
    "password": "qwerty123",
    "name": "John Doe",
    "role": "Administrator"
}   

###

PUT http://localhost:8080/api/users/update/1 HTTP/1.1
Content-Type: application/json

{
    "username": "jane",
    "password": "update123",
    "name": "Jane Doe",
    "role": "Administrator"
}   

###

GET http://localhost:8080/api/users HTTP/1.1

###

GET http://localhost:8080/api/users/2 HTTP/1.1

###

DELETE http://localhost:8080/api/users/delete/1 HTTP/1.1